config/routes.rb
Sharebox::Application.routes.draw do

  resources :folders

  resources :assets

  match "assets/get/:id" => "assets#get", :as => "download"

  match "browse/:folder_id" => "home#browse", :as => "browse"

  match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"

  match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file"

  match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"

  devise_for :users

  root :to => "home#index"

  match "home/share" => "home#share"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      #show folders shared by others
      @being_shared_folders = current_user.shared_folders_by_others

      #show only root folders
      @folders = current_user.folders.roots
      #show only root files
      @assets = current_user.assets.where("folder_id is NULL").order("uploaded_file_file_name desc")
    end
  end

  def browse
    #first find the current folder within own folders
    @current_folder = current_user.folders.find_by_id(params[:folder_id])
    @is_this_folder_being_shared = false if @current_folder #just an instance variable to help hiding buttons on View

    #if not found in own folders, find it in being_shared_folders
    if @current_folder.nil?
      folder = Folder.find_by_id(params[:folder_id])

      @current_folder ||= folder if current_user.has_share_access?(folder)
      @is_this_folder_being_shared = true if @current_folder #just an instance variable to help hiding buttons on View

    end

    if @current_folder
      #if under a sub folder, we shouldn't see shared folders
      @being_shared_folders = []

      #show folders under this current folder
      @folders = @current_folder.children

      #show only files under this current folder
      @assets = @current_folder.assets.order("uploaded_file_file_name desc")

      render :action => "index"
    else
      flash[:error] = "Don't be cheeky! Mind your own assets!"
      redirect_to root_url
    end
  end


  def share
    #first, we need to separate the emails with the comma
    email_addresses = params[:email_addresses].split(",")

    email_addresses.each do |email_address|
      #save the details in the ShareFolder table
      @shared_folder = current_user.shared_folders.new
      @shared_folder.folder_id = params[:folder_id]
      @shared_folder.shared_email = email_address

      #getting the shared user id right the owner the email has already signed up with ShareBox
      #if not, the field "shared_user_id" will be left nil for now.
      shared_user = User.find_by_email(email_address)
      @shared_folder.shared_user_id = shared_user.id if shared_user

      @shared_folder.message = params[:message]
      @shared_folder.save

      #now we need to send email to the Shared User
      UserMailer.invitation_to_share(@shared_folder).deliver
    end

    #since this action is mainly for ajax (javascript request), we'll respond with js file back (refer to share.js.erb)
    respond_to do |format|
      format.js {
      }
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_breadcrumbs.html.erb
<div class="breadcrumbs">
  <% if @current_folder #checking if we are under any folder %>
      <%= link_to "ShareBox", root_url %>
      <% @current_folder.ancestors.reverse.each do |folder| %>
          » <%= link_to folder.name, browse_path(folder) %>
      <% end %>
      »  <%= @current_folder.name %>
  <% else #if we are not under any folder%>
      ShareBox
  <% end %>
</div>

app/views/home/index.html.erb
<% unless user_signed_in? %>
    <h1>Welcome to ShareBox</h1>
    <p>File sharing web application you can't ignore.</p>

<% else %>
    <div id="menu">
      <% unless @is_this_folder_being_shared %>
          <ul id="top_menu">
            <% if @current_folder %>
                <li><%= link_to "Upload", new_sub_file_path(@current_folder) %></li>
                <li><%= link_to "New Folder", new_sub_folder_path(@current_folder) %></li>
            <% else %>
                <li><%= link_to "Upload", new_asset_path %></li>
                <li><%= link_to "New Folder", new_folder_path %></li>
            <% end %>
          </ul>
      <% else %>
          <h3>This folder is being shared to you by <%= @current_folder.user.name %></h3>
      <% end %>
    </div>

    <%= render :partial => "breadcrumbs" %>

    <div class="asset_list">
      <!-- Listing Shared Folders (the folders shared by others) -->
      <% @being_shared_folders.each do |folder| %>
          <div class="asset_details <%= folder.shared? ? 'shared_folder' : 'folder' %>" id="folder_<%= folder.id %>">
            <div class="file_name"><%= link_to folder.name, browse_path(folder) %></div>
            <div class="file_size">-</div>
            <div class="file_last_updated">-</div>
            <div class="actions">
            </div>
          </div>
      <% end %>

      <!-- Listing Folders -->
      <% @folders.each do |folder| %>
          <div class="asset_details <%= folder.shared? ? 'shared_folder' : 'folder' %>" id="folder_<%= folder.id %>">
            <div class="file_name"><%= link_to folder.name, browse_path(folder) %></div>
            <div class="file_size"> - </div>
            <div class="file_last_updated"> - </div>
            <div class="actions">
              <div class="share">
                <%= link_to "Share", "#", :folder_id => folder.id, :folder_name => folder.name unless @is_this_folder_being_shared%>
              </div>
              <div class="rename">
                <%= link_to "Rename", rename_folder_path(folder) unless @is_this_folder_being_shared%>
              </div>
              <div class="delete">
                <%= link_to "Delete", folder, :confirm => 'Are you sure to delete the folder and all of its contents?', :method => :delete unless @is_this_folder_being_shared%>
              </div>
            </div>
          </div>
      <% end%>

      <!-- Listing Files -->
      <% @assets.each do |asset| %>
          <div class="asset_details file">
            <div class="file_name"><%= link_to asset.file_name, download_url(asset) %></div>
            <div class="file_size"><%= number_to_human_size(asset.file_size, :precision => 2) %></div>
            <div class="file_last_updated"><%= asset.uploaded_file_updated_at %></div>
            <div class="actions">
              <div class="download">
                <%= link_to "Download", download_url(asset) %>
              </div>
              <div class="delete">
                <%= link_to "Delete", asset, :confirm => 'Are you sure?', :method => :delete unless @is_this_folder_being_shared%>
              </div>
            </div>
          </div>
      <% end %>
    </div>




    <div id="invitation_form" title="Invite others to share" style="display:none">
      <%= form_tag '/home/share' do -%>
          <label for="email_addresses">Enter recipient email addresses here</label><br />
          <%= text_field_tag 'email_addresses', "", :class => 'text ui-widget-content ui-corner-all'%>
          <br /><br />
          <label for="message">Optional message</label><br />
          <%= text_area_tag 'message',"",  :class => 'text ui-widget-content ui-corner-all'%>
          <%= hidden_field_tag "folder_id" %>
      <% end -%>
    </div>
<% end %>

app/views/home/share.js.erb
// closing the dialog box
$("#invitation_form").dialog("close");

// make sure we don't display the flash notice more than once
$("#flash_notice").remove();

// showing a flash message
$("#container").prepend("<div id=\"flash_notice\">Successfully shared the folder</div>");

// removing the CSS class 'folder'
$("#folder_<%= params[:folder_id] %>").removeClass("folder");

// adding the CSS class 'shared_folder'
$("#folder_<%= params[:folder_id] %>").addClass("shared_folder");